[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
gold_token = "GD4bYRVDAQyWuGqjuPJAds29DVJquUEBXfMRLiytBkVs"
transfer_hook_gatekeeper = "Bx71tovdDHUDwqFLmUc8NXRAG9P33kX59wjRYejM6Cj7"

[programs.localnet]
gold_token = "GD4bYRVDAQyWuGqjuPJAds29DVJquUEBXfMRLiytBkVs"
transfer_hook_gatekeeper = "Bx71tovdDHUDwqFLmUc8NXRAG9P33kX59wjRYejM6Cj7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "tests/metaplex_token_metadata.so"
