[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
gold_token = "3n4HRfj9SByGYGAHyyBMRTg9vx5K7hrMLiWQk1ajTPep"
transfer_hook_gatekeeper = "8n1czd3nT2mpgAcqayj8bfPXS9dtMKFHSe3Tz2v1PM3V"

[programs.localnet]
gold_token = "3n4HRfj9SByGYGAHyyBMRTg9vx5K7hrMLiWQk1ajTPep"
transfer_hook_gatekeeper = "8n1czd3nT2mpgAcqayj8bfPXS9dtMKFHSe3Tz2v1PM3V"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "tests/metaplex_token_metadata.so"
